@isTest
public class S360_Base_ProgressPathController_Test {
// 	@isTest
//     public static void testCheckFieldValue(){
//         Account acc = new Account();
//         acc.S360_FA__SLA__c = 'Gold';
//         acc.Name='test';
//         insert acc;
//         System.debug(acc.Id);
//         Account ac1 = S360_Base_ProgressPathController.checkFieldValue('S360_FA__SLA__c', acc.Id, 'Account');
//         System.assertEquals(ac1.Id, acc.Id);
//         System.assertEquals(ac1.S360_FA__SLA__c, acc.S360_FA__SLA__c);
//     }
}